/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QuanLyPhongKham.UI;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author OS
 */
public class Manhinhchinnh extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhongKham
     */
    public Manhinhchinnh() {
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTong = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblXinChao = new javax.swing.JLabel();
        lblTieuDe = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAnhNV = new rojerusan.RSFotoCircle();
        pnlLeft = new javax.swing.JPanel();
        lblDanhMuc = new javax.swing.JLabel();
        pnlQuanLyBacSi = new javax.swing.JPanel();
        lblIconBacSi = new javax.swing.JLabel();
        lblQuanLyBacSi = new javax.swing.JLabel();
        pnlQuanLyNhanVien = new javax.swing.JPanel();
        lblIconNhanVien = new javax.swing.JLabel();
        lblQuanLyNhanVien = new javax.swing.JLabel();
        pnlQuanLyBenhNhan = new javax.swing.JPanel();
        lblIconBenhNhan = new javax.swing.JLabel();
        lblQuanLyBenhNhan = new javax.swing.JLabel();
        pnlQuanLyHoaDon = new javax.swing.JPanel();
        lblIconHoaDon = new javax.swing.JLabel();
        lblQuanLyHoaDon = new javax.swing.JLabel();
        pnlQuanLyPhieuKham = new javax.swing.JPanel();
        lblIconPhieuKham = new javax.swing.JLabel();
        lblQuanLyPhieuKham = new javax.swing.JLabel();
        pnlQuanLyThuoc = new javax.swing.JPanel();
        lblIconThuoc = new javax.swing.JLabel();
        lblQuanLyThuoc = new javax.swing.JLabel();
        pnlQuanLyThongKe = new javax.swing.JPanel();
        lblIconThongKe = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        pnlDichVu = new javax.swing.JPanel();
        lblIconDichVu = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        btnDangXuat = new rojeru_san.complementos.RSButtonHover();
        pnlQuanLyThongKe1 = new javax.swing.JPanel();
        lblIconThongKe1 = new javax.swing.JLabel();
        lblThongKe1 = new javax.swing.JLabel();
        pnlQuanLyThongKe2 = new javax.swing.JPanel();
        lblIconThongKe2 = new javax.swing.JLabel();
        lblThongKe2 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblbacsi = new javax.swing.JLabel();
        lblphieukham = new javax.swing.JLabel();
        lblnhanvien = new javax.swing.JLabel();
        lblthuoc = new javax.swing.JLabel();
        lblhoadon = new javax.swing.JLabel();
        lbldichvu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BỆNH NHÂN\n");

        pnlTong.setBackground(new java.awt.Color(255, 255, 255));

        pnlHeader.setBackground(new java.awt.Color(51, 153, 255));

        lblXinChao.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblXinChao.setForeground(new java.awt.Color(255, 208, 175));
        lblXinChao.setText("Xin chào, ");

        lblTieuDe.setBackground(new java.awt.Color(0, 0, 0));
        lblTieuDe.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("PHÒNG KHÁM AN NHIÊN");

        lblDay.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDay.setText("dd/MM/yyyy");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("MANG ĐẾN SỰ BÌNH YÊN");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                        .addGap(105, 105, 105)
                        .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDay)
                            .addComponent(lblTieuDe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblXinChao)
                .addGap(34, 34, 34))
        );

        pnlLeft.setBackground(new java.awt.Color(54, 70, 78));
        pnlLeft.setForeground(new java.awt.Color(54, 70, 78));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDanhMuc.setBackground(new java.awt.Color(54, 70, 78));
        lblDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-menu-30.png"))); // NOI18N
        lblDanhMuc.setOpaque(true);
        lblDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseExited(evt);
            }
        });
        pnlLeft.add(lblDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 40));

        pnlQuanLyBacSi.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyBacSi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconBacSi.setBackground(new java.awt.Color(54, 70, 78));
        lblIconBacSi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconBacSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_doctor_male_30px.png"))); // NOI18N
        lblIconBacSi.setToolTipText("Quản Lý Bác Sĩ");
        lblIconBacSi.setOpaque(true);
        lblIconBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseExited(evt);
            }
        });
        pnlQuanLyBacSi.add(lblIconBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyBacSi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyBacSi.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyBacSi.setText("Quản Lý Bác Sĩ");
        lblQuanLyBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseExited(evt);
            }
        });
        pnlQuanLyBacSi.add(lblQuanLyBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 40));

        pnlQuanLyNhanVien.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconNhanVien.setBackground(new java.awt.Color(54, 70, 78));
        lblIconNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_manager_30px.png"))); // NOI18N
        lblIconNhanVien.setToolTipText("Quản Lý Nhân Viên");
        lblIconNhanVien.setOpaque(true);
        lblIconNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseExited(evt);
            }
        });
        pnlQuanLyNhanVien.add(lblIconNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyNhanVien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        lblQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseExited(evt);
            }
        });
        pnlQuanLyNhanVien.add(lblQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 40));

        pnlQuanLyBenhNhan.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyBenhNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconBenhNhan.setBackground(new java.awt.Color(54, 70, 78));
        lblIconBenhNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-male-user-23.png"))); // NOI18N
        lblIconBenhNhan.setToolTipText("Quản Lý Bệnh Nhân");
        lblIconBenhNhan.setOpaque(true);
        lblIconBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseExited(evt);
            }
        });
        pnlQuanLyBenhNhan.add(lblIconBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyBenhNhan.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyBenhNhan.setText("Quản Lý Bệnh Nhân");
        lblQuanLyBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseExited(evt);
            }
        });
        pnlQuanLyBenhNhan.add(lblQuanLyBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 40));

        pnlQuanLyHoaDon.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconHoaDon.setBackground(new java.awt.Color(54, 70, 78));
        lblIconHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dollar_place_marker_30px.png"))); // NOI18N
        lblIconHoaDon.setToolTipText("Quản Lý Hoá Đơn");
        lblIconHoaDon.setOpaque(true);
        lblIconHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseExited(evt);
            }
        });
        pnlQuanLyHoaDon.add(lblIconHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyHoaDon.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyHoaDon.setText("Quản Lý Hoá Đơn");
        lblQuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseExited(evt);
            }
        });
        pnlQuanLyHoaDon.add(lblQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 40));

        pnlQuanLyPhieuKham.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyPhieuKham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconPhieuKham.setBackground(new java.awt.Color(54, 70, 78));
        lblIconPhieuKham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPhieuKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_ticket_30px.png"))); // NOI18N
        lblIconPhieuKham.setToolTipText("Quản Lý Phiếu Khám");
        lblIconPhieuKham.setOpaque(true);
        lblIconPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseExited(evt);
            }
        });
        pnlQuanLyPhieuKham.add(lblIconPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyPhieuKham.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyPhieuKham.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyPhieuKham.setText("Quản Lý Phiếu Khám\n");
        lblQuanLyPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseExited(evt);
            }
        });
        pnlQuanLyPhieuKham.add(lblQuanLyPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 20));

        pnlLeft.add(pnlQuanLyPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 40));

        pnlQuanLyThuoc.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThuoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThuoc.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_clinic_30px.png"))); // NOI18N
        lblIconThuoc.setToolTipText("Quản Lý Thuốc");
        lblIconThuoc.setOpaque(true);
        lblIconThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseExited(evt);
            }
        });
        pnlQuanLyThuoc.add(lblIconThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyThuoc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyThuoc.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyThuoc.setText("Quản Lý Thuốc");
        lblQuanLyThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseExited(evt);
            }
        });
        pnlQuanLyThuoc.add(lblQuanLyThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 40));

        pnlQuanLyThongKe.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThongKe.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-increase-23.png"))); // NOI18N
        lblIconThongKe.setToolTipText("Quản Lý Thống Kê");
        lblIconThongKe.setOpaque(true);
        lblIconThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseExited(evt);
            }
        });
        pnlQuanLyThongKe.add(lblIconThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblThongKe.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKe.setText("Thống kê bệnh nhân");
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeMouseExited(evt);
            }
        });
        pnlQuanLyThongKe.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 20));

        pnlLeft.add(pnlQuanLyThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 210, 40));

        pnlDichVu.setBackground(new java.awt.Color(54, 70, 78));
        pnlDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconDichVu.setBackground(new java.awt.Color(54, 70, 78));
        lblIconDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-magazine-23.png"))); // NOI18N
        lblIconDichVu.setToolTipText("Quản Lý Dịch Vụ");
        lblIconDichVu.setOpaque(true);
        lblIconDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconDichVuMouseExited(evt);
            }
        });
        pnlDichVu.add(lblIconDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblDichVu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(255, 255, 255));
        lblDichVu.setText("Quản Lý Dịch Vụ");
        lblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDichVuMouseExited(evt);
            }
        });
        pnlDichVu.add(lblDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 40));

        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 170, -1));

        pnlQuanLyThongKe1.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThongKe1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThongKe1.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThongKe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThongKe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-increase-23.png"))); // NOI18N
        lblIconThongKe1.setToolTipText("Quản Lý Thống Kê");
        lblIconThongKe1.setOpaque(true);
        lblIconThongKe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThongKe1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThongKe1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThongKe1MouseExited(evt);
            }
        });
        pnlQuanLyThongKe1.add(lblIconThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblThongKe1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThongKe1.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKe1.setText("Quản lý chi tiết dịch vụ");
        lblThongKe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKe1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongKe1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKe1MouseExited(evt);
            }
        });
        pnlQuanLyThongKe1.add(lblThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 20));

        pnlLeft.add(pnlQuanLyThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 40));

        pnlQuanLyThongKe2.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThongKe2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThongKe2.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThongKe2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThongKe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-increase-23.png"))); // NOI18N
        lblIconThongKe2.setToolTipText("Quản Lý Thống Kê");
        lblIconThongKe2.setOpaque(true);
        lblIconThongKe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThongKe2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThongKe2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThongKe2MouseExited(evt);
            }
        });
        pnlQuanLyThongKe2.add(lblIconThongKe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblThongKe2.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThongKe2.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKe2.setText("Đổi mật khẩu");
        lblThongKe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKe2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongKe2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKe2MouseExited(evt);
            }
        });
        pnlQuanLyThongKe2.add(lblThongKe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 20));

        pnlLeft.add(pnlQuanLyThongKe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 210, 40));

        pnlRight.setBackground(new java.awt.Color(0, 204, 204));
        pnlRight.setFocusable(false);
        pnlRight.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        lblbacsi.setBackground(new java.awt.Color(255, 255, 255));
        lblbacsi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblbacsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbacsi.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\Quanlyphongkham1\\QuanLyPhongKham\\src\\com\\QuanLyPhongKham\\Icon\\scientist_man_70px.png")); // NOI18N
        lblbacsi.setText("Quản Lý Bác Sĩ");
        lblbacsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbacsiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbacsiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbacsiMouseExited(evt);
            }
        });
        pnlRight.add(lblbacsi);

        lblphieukham.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblphieukham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphieukham.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\Quanlyphongkham1\\QuanLyPhongKham\\src\\com\\QuanLyPhongKham\\Icon\\check_70px.png")); // NOI18N
        lblphieukham.setText("Quản Lý Phiếu Khám");
        lblphieukham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblphieukhamMouseClicked(evt);
            }
        });
        pnlRight.add(lblphieukham);

        lblnhanvien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblnhanvien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnhanvien.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\Quanlyphongkham1\\QuanLyPhongKham\\src\\com\\QuanLyPhongKham\\Icon\\management_70px.png")); // NOI18N
        lblnhanvien.setText("Quản Lý Nhân Viên");
        lblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnhanvienMouseClicked(evt);
            }
        });
        pnlRight.add(lblnhanvien);

        lblthuoc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblthuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthuoc.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\Quanlyphongkham1\\QuanLyPhongKham\\src\\com\\QuanLyPhongKham\\Icon\\health_book_70px.png")); // NOI18N
        lblthuoc.setText("Quản Lý Thuốc");
        lblthuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthuocMouseClicked(evt);
            }
        });
        pnlRight.add(lblthuoc);

        lblhoadon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblhoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhoadon.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\Quanlyphongkham1\\QuanLyPhongKham\\src\\com\\QuanLyPhongKham\\Icon\\bill_70px.png")); // NOI18N
        lblhoadon.setText("Quản Lý Hóa Đơn");
        lblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhoadonMouseClicked(evt);
            }
        });
        pnlRight.add(lblhoadon);

        lbldichvu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbldichvu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldichvu.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\Quanlyphongkham1\\QuanLyPhongKham\\src\\com\\QuanLyPhongKham\\Icon\\management_70px.png")); // NOI18N
        lbldichvu.setText("Quản Lý Dịch Vụ");
        lbldichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldichvuMouseClicked(evt);
            }
        });
        pnlRight.add(lbldichvu);

        javax.swing.GroupLayout pnlTongLayout = new javax.swing.GroupLayout(pnlTong);
        pnlTong.setLayout(pnlTongLayout);
        pnlTongLayout.setHorizontalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlTongLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTongLayout.setVerticalGroup(
            pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTongLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(pnlRight, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x = 210;
    int i = 0;
    private void lblbacsiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbacsiMouseEntered
        //TODO add your handling code here:
        lblbacsi.setForeground(Color.white);
        lblbacsi.setBackground(new Color(255, 255, 143));
        lblbacsi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblbacsiMouseEntered

    private void lblbacsiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbacsiMouseExited
        //TODO add your handling code here:
        lblbacsi.setForeground(Color.black);
        lblbacsi.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_lblbacsiMouseExited

    private void lblbacsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbacsiMouseClicked
        // TODO add your handling code here:
        OpenBacSi();
    }//GEN-LAST:event_lblbacsiMouseClicked

    private void lblphieukhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblphieukhamMouseClicked
        // TODO add your handling code here:
        OpenPhieuKham();
    }//GEN-LAST:event_lblphieukhamMouseClicked

    private void lblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnhanvienMouseClicked
        // TODO add your handling code here:
        OpenNhanVien();
    }//GEN-LAST:event_lblnhanvienMouseClicked

    private void lblthuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthuocMouseClicked
        // TODO add your handling code here:
        OpenThuoc();
    }//GEN-LAST:event_lblthuocMouseClicked

    private void lblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhoadonMouseClicked
        // TODO add your handling code here:
        OpenHoaDon();
    }//GEN-LAST:event_lblhoadonMouseClicked

    private void lbldichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldichvuMouseClicked
        // TODO add your handling code here:
        OpenDichVu();
    }//GEN-LAST:event_lbldichvuMouseClicked

    private void lblThongKe1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKe1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThongKe1MouseExited

    private void lblThongKe1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKe1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThongKe1MouseEntered

    private void lblThongKe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKe1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThongKe1MouseClicked

    private void lblIconThongKe1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKe1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThongKe1MouseExited

    private void lblIconThongKe1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKe1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThongKe1MouseEntered

    private void lblIconThongKe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKe1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThongKe1MouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.OpenLogin();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void lblDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseExited
        NotHoverPanel(pnlDichVu, lblIconDichVu);
    }//GEN-LAST:event_lblDichVuMouseExited

    private void lblDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseEntered
        hoverPanel(pnlDichVu, lblIconDichVu);
    }//GEN-LAST:event_lblDichVuMouseEntered

    private void lblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseClicked
        this.OpenDichVu();
    }//GEN-LAST:event_lblDichVuMouseClicked

    private void lblIconDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconDichVuMouseExited
        NotHover(lblIconDichVu);
    }//GEN-LAST:event_lblIconDichVuMouseExited

    private void lblIconDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconDichVuMouseEntered
        hover(lblIconDichVu);
    }//GEN-LAST:event_lblIconDichVuMouseEntered

    private void lblIconDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconDichVuMouseClicked
        this.OpenDichVu();
    }//GEN-LAST:event_lblIconDichVuMouseClicked

    private void lblThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseExited
        NotHoverPanel(pnlQuanLyThongKe, lblIconThongKe);
    }//GEN-LAST:event_lblThongKeMouseExited

    private void lblThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseEntered
        hoverPanel(pnlQuanLyThongKe, lblIconThongKe);
    }//GEN-LAST:event_lblThongKeMouseEntered

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        try {
            this.OpenThongKe();
        } catch (SQLException ex) {
            Logger.getLogger(Manhinhchinnh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblIconThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseExited
        NotHover(lblIconThongKe);
    }//GEN-LAST:event_lblIconThongKeMouseExited

    private void lblIconThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseEntered
        hover(lblIconThongKe);
    }//GEN-LAST:event_lblIconThongKeMouseEntered

    private void lblIconThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseClicked
        try {
            this.OpenThongKe();
        } catch (SQLException ex) {
            Logger.getLogger(Manhinhchinnh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblIconThongKeMouseClicked

    private void lblQuanLyThuocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseExited
        NotHoverPanel(pnlQuanLyThuoc, lblIconThuoc);
    }//GEN-LAST:event_lblQuanLyThuocMouseExited

    private void lblQuanLyThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseEntered
        hoverPanel(pnlQuanLyThuoc, lblIconThuoc);
    }//GEN-LAST:event_lblQuanLyThuocMouseEntered

    private void lblQuanLyThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseClicked
        this.OpenThuoc();
    }//GEN-LAST:event_lblQuanLyThuocMouseClicked

    private void lblIconThuocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseExited
        NotHover(lblIconThuoc);
    }//GEN-LAST:event_lblIconThuocMouseExited

    private void lblIconThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseEntered
        hover(lblIconThuoc);
    }//GEN-LAST:event_lblIconThuocMouseEntered

    private void lblIconThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseClicked
        this.OpenThuoc();
    }//GEN-LAST:event_lblIconThuocMouseClicked

    private void lblQuanLyPhieuKhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseExited
        NotHoverPanel(pnlQuanLyPhieuKham, lblIconPhieuKham);
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseExited

    private void lblQuanLyPhieuKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseEntered
        hoverPanel(pnlQuanLyPhieuKham, lblIconPhieuKham);
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseEntered

    private void lblQuanLyPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseClicked
        this.OpenPhieuKham();
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseClicked

    private void lblIconPhieuKhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseExited
        NotHover(lblIconPhieuKham);
    }//GEN-LAST:event_lblIconPhieuKhamMouseExited

    private void lblIconPhieuKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseEntered
        hover(lblIconPhieuKham);
    }//GEN-LAST:event_lblIconPhieuKhamMouseEntered

    private void lblIconPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseClicked
        this.OpenPhieuKham();
    }//GEN-LAST:event_lblIconPhieuKhamMouseClicked

    private void lblQuanLyHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseExited
        NotHoverPanel(pnlQuanLyHoaDon, lblIconHoaDon);
    }//GEN-LAST:event_lblQuanLyHoaDonMouseExited

    private void lblQuanLyHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseEntered
        hoverPanel(pnlQuanLyHoaDon, lblIconHoaDon);
    }//GEN-LAST:event_lblQuanLyHoaDonMouseEntered

    private void lblQuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseClicked
        this.OpenHoaDon();
    }//GEN-LAST:event_lblQuanLyHoaDonMouseClicked

    private void lblIconHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseExited
        NotHover(lblIconHoaDon);
    }//GEN-LAST:event_lblIconHoaDonMouseExited

    private void lblIconHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseEntered
        hover(lblIconHoaDon);
    }//GEN-LAST:event_lblIconHoaDonMouseEntered

    private void lblIconHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseClicked
        this.OpenHoaDon();
    }//GEN-LAST:event_lblIconHoaDonMouseClicked

    private void lblQuanLyBenhNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseExited
        NotHoverPanel(pnlQuanLyBenhNhan, lblIconBenhNhan);
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseExited

    private void lblQuanLyBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseEntered
        hoverPanel(pnlQuanLyBenhNhan, lblIconBenhNhan);
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseEntered

    private void lblQuanLyBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseClicked
        this.OpenBenhNhan();
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseClicked

    private void lblIconBenhNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseExited
        //        NotHover(lblIconBenhNhan);
    }//GEN-LAST:event_lblIconBenhNhanMouseExited

    private void lblIconBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseEntered
        //        hover(lblIconBenhNhan);
    }//GEN-LAST:event_lblIconBenhNhanMouseEntered

    private void lblIconBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseClicked
        this.OpenBenhNhan();
    }//GEN-LAST:event_lblIconBenhNhanMouseClicked

    private void lblQuanLyNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseExited
        NotHoverPanel(pnlQuanLyNhanVien, lblIconNhanVien);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseExited

    private void lblQuanLyNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseEntered
        hoverPanel(pnlQuanLyNhanVien, lblIconNhanVien);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseEntered

    private void lblQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseClicked
        this.OpenNhanVien();
    }//GEN-LAST:event_lblQuanLyNhanVienMouseClicked

    private void lblIconNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseExited
        NotHover(lblIconNhanVien);
    }//GEN-LAST:event_lblIconNhanVienMouseExited

    private void lblIconNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseEntered
        hover(lblIconNhanVien);
    }//GEN-LAST:event_lblIconNhanVienMouseEntered

    private void lblIconNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseClicked
        this.OpenNhanVien();
    }//GEN-LAST:event_lblIconNhanVienMouseClicked

    private void lblQuanLyBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseExited
        NotHoverPanel(pnlQuanLyBacSi, lblIconBacSi);
    }//GEN-LAST:event_lblQuanLyBacSiMouseExited

    private void lblQuanLyBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseEntered
        hoverPanel(pnlQuanLyBacSi, lblIconBacSi);
    }//GEN-LAST:event_lblQuanLyBacSiMouseEntered

    private void lblQuanLyBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseClicked
        this.OpenBacSi();
    }//GEN-LAST:event_lblQuanLyBacSiMouseClicked

    private void lblIconBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseExited
        //NotHover(lblIconBacSi);
    }//GEN-LAST:event_lblIconBacSiMouseExited

    private void lblIconBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseEntered
        //hover(lblIconBacSi);
    }//GEN-LAST:event_lblIconBacSiMouseEntered

    private void lblIconBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseClicked
        this.OpenBacSi();
    }//GEN-LAST:event_lblIconBacSiMouseClicked

    private void lblDanhMucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseExited
        NotHover(lblDanhMuc);
    }//GEN-LAST:event_lblDanhMucMouseExited

    private void lblDanhMucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseEntered
        hover(lblDanhMuc);
    }//GEN-LAST:event_lblDanhMucMouseEntered

    private void lblDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseClicked
        if (x == 210) {
            pnlLeft.setSize(210, 790);
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        for (i = 210; i >= 60; i--) {
                            Thread.sleep(1, 5);
                            pnlLeft.setSize(i, 790);
                            pnlRight.setLocation(60, 100);
                            pnlRight.setSize(1340, 790);
                            btnDangXuat.show(false);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            th.start();
            x = 60;
        } else if (x == 60) {
            pnlLeft.setSize(x, 790);
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        for (i = 60; i <= x; i++) {
                            Thread.sleep(1);
                            pnlLeft.setSize(i, 790);
                            pnlRight.setLocation(210, 110);
                            pnlRight.setSize(1190, 790);
                            btnDangXuat.show(true);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            th.start();
            x = 210;
        }
    }//GEN-LAST:event_lblDanhMucMouseClicked

    private void lblIconThongKe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKe2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThongKe2MouseClicked

    private void lblIconThongKe2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKe2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThongKe2MouseEntered

    private void lblIconThongKe2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKe2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThongKe2MouseExited

    private void lblThongKe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKe2MouseClicked
        // TODO add your handling code here:
        this.OpenQuenpass();
    }//GEN-LAST:event_lblThongKe2MouseClicked

    private void lblThongKe2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKe2MouseEntered
        // TODO add your handling code here:
        hoverPanel(pnlQuanLyThongKe2, lblIconThongKe2);
    }//GEN-LAST:event_lblThongKe2MouseEntered

    private void lblThongKe2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKe2MouseExited
        // TODO add your handling code here:
        NotHoverPanel(pnlQuanLyThongKe2, lblIconThongKe2);
    }//GEN-LAST:event_lblThongKe2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBenhNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manhinhchinnh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover btnDangXuat;
    private javax.swing.JLabel jLabel1;
    private rojerusan.RSFotoCircle lblAnhNV;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblIconBacSi;
    private javax.swing.JLabel lblIconBenhNhan;
    private javax.swing.JLabel lblIconDichVu;
    private javax.swing.JLabel lblIconHoaDon;
    private javax.swing.JLabel lblIconNhanVien;
    private javax.swing.JLabel lblIconPhieuKham;
    private javax.swing.JLabel lblIconThongKe;
    private javax.swing.JLabel lblIconThongKe1;
    private javax.swing.JLabel lblIconThongKe2;
    private javax.swing.JLabel lblIconThuoc;
    private javax.swing.JLabel lblQuanLyBacSi;
    private javax.swing.JLabel lblQuanLyBenhNhan;
    private javax.swing.JLabel lblQuanLyHoaDon;
    private javax.swing.JLabel lblQuanLyNhanVien;
    private javax.swing.JLabel lblQuanLyPhieuKham;
    private javax.swing.JLabel lblQuanLyThuoc;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblThongKe1;
    private javax.swing.JLabel lblThongKe2;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblXinChao;
    private javax.swing.JLabel lblbacsi;
    private javax.swing.JLabel lbldichvu;
    private javax.swing.JLabel lblhoadon;
    private javax.swing.JLabel lblnhanvien;
    private javax.swing.JLabel lblphieukham;
    private javax.swing.JLabel lblthuoc;
    private javax.swing.JPanel pnlDichVu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlQuanLyBacSi;
    private javax.swing.JPanel pnlQuanLyBenhNhan;
    private javax.swing.JPanel pnlQuanLyHoaDon;
    private javax.swing.JPanel pnlQuanLyNhanVien;
    private javax.swing.JPanel pnlQuanLyPhieuKham;
    private javax.swing.JPanel pnlQuanLyThongKe;
    private javax.swing.JPanel pnlQuanLyThongKe1;
    private javax.swing.JPanel pnlQuanLyThongKe2;
    private javax.swing.JPanel pnlQuanLyThuoc;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTong;
    // End of variables declaration//GEN-END:variables
    private void init() {
        //hoverPanel(pnlQuanLyBenhNhan, lblIconBenhNhan);
        setLocationRelativeTo(null);
        this.LoadNgay();
        new Chao(this, true).setVisible(true);
        new dangnhap(this, true).setVisible(true);

    }

    //Hover màu
    private void hover(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void NotHover(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(54, 70, 78));
    }

    private void hoverPanel(JPanel pnl, JLabel lbl) {
        pnl.setBackground(new java.awt.Color(53, 162, 107));
        lbl.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void NotHoverPanel(JPanel pnl, JLabel lbl) {
        pnl.setBackground(new java.awt.Color(54, 70, 78));
        lbl.setBackground(new java.awt.Color(54, 70, 78));
    }

    private void LoadNgay() {
        new javax.swing.Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date date = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                //SimpleDateFormat sdf1 = new SimpleDateFormat("hh:mm:ss a");
                String day = sdf.format(date);
                //String time = sdf1.format(date);
                lblDay.setText(day);
                //lblTime.setText(time);
            }
        }).start();
    }

    private void OpenBacSi() {
        //this.dispose();
        new QuanLyBacSi().setVisible(true);
    }

    private void OpenBenhNhan() {
        //this.dispose();
        new QuanLyBenhNhan().setVisible(true);
    }

    private void OpenNhanVien() {
        //this.dispose();
        new QuanLyNhanVien().setVisible(true);
    }

    private void OpenHoaDon() {
        //this.dispose();
        new QuanLyHoaDon().setVisible(true);
    }

    private void OpenPhieuKham() {
        //this.dispose();
        new QuanLyPhieuKham().setVisible(true);
    }

    private void OpenThuoc() {
        //this.dispose();
        new QuanLyThuoc().setVisible(true);
    }

    private void OpenDichVu() {
        //this.dispose();
        new QuanLyDichVu().setVisible(true);
    }

    private void OpenLogin() {
        //this.dispose();
        new dangnhap(this, true).setVisible(true);
    }

    private void OpenThongKe() throws SQLException {
        //this.dispose();
        new ThongKeBenhNhan().setVisible(true);
    }

    private void OpenQuenpass() {
        //this.dispose();
        new DoiMatKhau(this, rootPaneCheckingEnabled).setVisible(true);
    }
}
