/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QuanLyPhongKham.UI;

import com.QuanLyPhongKham.DAO.dichVuDAO;
import com.QuanLyPhongKham.DAO.loaithuocDAO;
import com.QuanLyPhongKham.DAO.phieukhamDAO;
import com.QuanLyPhongKham.DAO.thuocDAO;
import com.QuanLyPhongKham.Model.DichVu;
import com.QuanLyPhongKham.Model.LoaiThuoc;
import com.QuanLyPhongKham.Model.PhieuKham;
import com.QuanLyPhongKham.Model.Thuoc;
import com.QuanLyPhongKham.Utilities.XDate;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OS
 */
public class QuanLyToaThuoc extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhongKham
     */
    public QuanLyToaThuoc() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTong = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblXinChao = new javax.swing.JLabel();
        lblTieuDe = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAnhNV = new rojerusan.RSFotoCircle();
        pnlLeft = new javax.swing.JPanel();
        lblDanhMuc = new javax.swing.JLabel();
        pnlQuanLyBacSi = new javax.swing.JPanel();
        lblIconBacSi = new javax.swing.JLabel();
        lblQuanLyBacSi = new javax.swing.JLabel();
        pnlQuanLyNhanVien = new javax.swing.JPanel();
        lblIconNhanVien = new javax.swing.JLabel();
        lblQuanLyNhanVien = new javax.swing.JLabel();
        pnlQuanLyBenhNhan = new javax.swing.JPanel();
        lblIconBenhNhan = new javax.swing.JLabel();
        lblQuanLyBenhNhan = new javax.swing.JLabel();
        pnlQuanLyHoaDon = new javax.swing.JPanel();
        lblIconHoaDon = new javax.swing.JLabel();
        lblQuanLyHoaDon = new javax.swing.JLabel();
        pnlQuanLyPhieuKham = new javax.swing.JPanel();
        lblIconPhieuKham = new javax.swing.JLabel();
        lblQuanLyPhieuKham = new javax.swing.JLabel();
        pnlQuanLyThuoc = new javax.swing.JPanel();
        lblIconThuoc = new javax.swing.JLabel();
        lblQuanLyThuoc = new javax.swing.JLabel();
        pnlQuanLyThongKe = new javax.swing.JPanel();
        lblIconThongKe = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        pnlDichVu = new javax.swing.JPanel();
        lblIconDichVu = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        btnDangXuat = new rojeru_san.complementos.RSButtonHover();
        pnlRight = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblThuoc = new javax.swing.JLabel();
        lblDSPhieuKham = new javax.swing.JLabel();
        pnlCard = new javax.swing.JPanel();
        pnlThuoc = new javax.swing.JPanel();
        txtTimKiemTenThuoc = new javax.swing.JLabel();
        cboLoaiThuoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSThuoc = new rojeru_san.complementos.RSTableMetro();
        lblThoaiThuoc = new javax.swing.JLabel();
        txtTimKiemThuoc = new javax.swing.JTextField();
        pnlDSPhieuKham = new javax.swing.JPanel();
        txtTimKiemDichVu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSPhieuKham = new rojeru_san.complementos.RSTableMetro();
        btnTim = new rojeru_san.complementos.RSButtonHover();
        jLabel5 = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new rojeru_san.complementos.RSTableMetro();
        btnThem = new rojeru_san.complementos.RSButtonHover();
        btnInHoaDon = new rojeru_san.complementos.RSButtonHover();
        btnDanhSachHoaDon = new rojeru_san.complementos.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ HOÁ ĐƠN\n");

        pnlTong.setBackground(new java.awt.Color(255, 255, 255));
        pnlTong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(51, 153, 255));

        lblXinChao.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblXinChao.setText("Xin chào, ");

        lblTieuDe.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("PHÒNG KHÁM AN NHIÊN");

        lblDay.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDay.setText("dd/MM/yyyy");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANG ĐẾN SỰ BÌNH YÊN");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTieuDe)
                            .addComponent(lblDay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblXinChao)
                .addGap(34, 34, 34))
        );

        pnlTong.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 100));

        pnlLeft.setBackground(new java.awt.Color(54, 70, 78));
        pnlLeft.setForeground(new java.awt.Color(54, 70, 78));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDanhMuc.setBackground(new java.awt.Color(54, 70, 78));
        lblDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-menu-30.png"))); // NOI18N
        lblDanhMuc.setOpaque(true);
        lblDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseExited(evt);
            }
        });
        pnlLeft.add(lblDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 40));

        pnlQuanLyBacSi.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyBacSi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconBacSi.setBackground(new java.awt.Color(54, 70, 78));
        lblIconBacSi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconBacSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_doctor_male_30px.png"))); // NOI18N
        lblIconBacSi.setToolTipText("Quản Lý Bác Sĩ");
        lblIconBacSi.setOpaque(true);
        lblIconBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseExited(evt);
            }
        });
        pnlQuanLyBacSi.add(lblIconBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyBacSi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyBacSi.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyBacSi.setText("Quản Lý Bác Sĩ");
        lblQuanLyBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseExited(evt);
            }
        });
        pnlQuanLyBacSi.add(lblQuanLyBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 40));

        pnlQuanLyNhanVien.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconNhanVien.setBackground(new java.awt.Color(54, 70, 78));
        lblIconNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_manager_30px.png"))); // NOI18N
        lblIconNhanVien.setToolTipText("Quản Lý Nhân Viên");
        lblIconNhanVien.setOpaque(true);
        lblIconNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseExited(evt);
            }
        });
        pnlQuanLyNhanVien.add(lblIconNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyNhanVien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        lblQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseExited(evt);
            }
        });
        pnlQuanLyNhanVien.add(lblQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 40));

        pnlQuanLyBenhNhan.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyBenhNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconBenhNhan.setBackground(new java.awt.Color(54, 70, 78));
        lblIconBenhNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-male-user-23.png"))); // NOI18N
        lblIconBenhNhan.setToolTipText("Quản Lý Bệnh Nhân");
        lblIconBenhNhan.setOpaque(true);
        lblIconBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseExited(evt);
            }
        });
        pnlQuanLyBenhNhan.add(lblIconBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyBenhNhan.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyBenhNhan.setText("Quản Lý Bệnh Nhân");
        lblQuanLyBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseExited(evt);
            }
        });
        pnlQuanLyBenhNhan.add(lblQuanLyBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 40));

        pnlQuanLyHoaDon.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconHoaDon.setBackground(new java.awt.Color(54, 70, 78));
        lblIconHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dollar_place_marker_30px.png"))); // NOI18N
        lblIconHoaDon.setToolTipText("Quản Lý Hoá Đơn");
        lblIconHoaDon.setOpaque(true);
        lblIconHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseExited(evt);
            }
        });
        pnlQuanLyHoaDon.add(lblIconHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyHoaDon.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyHoaDon.setText("Quản Lý Hoá Đơn");
        lblQuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseExited(evt);
            }
        });
        pnlQuanLyHoaDon.add(lblQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 40));

        pnlQuanLyPhieuKham.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyPhieuKham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconPhieuKham.setBackground(new java.awt.Color(54, 70, 78));
        lblIconPhieuKham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPhieuKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_ticket_30px.png"))); // NOI18N
        lblIconPhieuKham.setToolTipText("Quản Lý Phiếu Khám");
        lblIconPhieuKham.setOpaque(true);
        lblIconPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseExited(evt);
            }
        });
        pnlQuanLyPhieuKham.add(lblIconPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyPhieuKham.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyPhieuKham.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyPhieuKham.setText("Quản Lý Phiếu Khám\n");
        lblQuanLyPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseExited(evt);
            }
        });
        pnlQuanLyPhieuKham.add(lblQuanLyPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 20));

        pnlLeft.add(pnlQuanLyPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 40));

        pnlQuanLyThuoc.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThuoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThuoc.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_clinic_30px.png"))); // NOI18N
        lblIconThuoc.setToolTipText("Quản Lý Thuốc");
        lblIconThuoc.setOpaque(true);
        lblIconThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseExited(evt);
            }
        });
        pnlQuanLyThuoc.add(lblIconThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyThuoc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyThuoc.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyThuoc.setText("Quản Lý Thuốc");
        lblQuanLyThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseExited(evt);
            }
        });
        pnlQuanLyThuoc.add(lblQuanLyThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 40));

        pnlQuanLyThongKe.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThongKe.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-increase-23.png"))); // NOI18N
        lblIconThongKe.setToolTipText("Quản Lý Thống Kê");
        lblIconThongKe.setOpaque(true);
        lblIconThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseExited(evt);
            }
        });
        pnlQuanLyThongKe.add(lblIconThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblThongKe.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKe.setText("Thống Kê");
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeMouseExited(evt);
            }
        });
        pnlQuanLyThongKe.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 40));

        pnlDichVu.setBackground(new java.awt.Color(54, 70, 78));
        pnlDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconDichVu.setBackground(new java.awt.Color(54, 70, 78));
        lblIconDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-magazine-23.png"))); // NOI18N
        lblIconDichVu.setToolTipText("Quản Lý Dịch Vụ");
        lblIconDichVu.setOpaque(true);
        lblIconDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconDichVuMouseExited(evt);
            }
        });
        pnlDichVu.add(lblIconDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblDichVu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(255, 255, 255));
        lblDichVu.setText("Quản Lý Dịch Vụ");
        lblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDichVuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDichVuMouseExited(evt);
            }
        });
        pnlDichVu.add(lblDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 40));

        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnlLeft.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 170, -1));

        pnlTong.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 790));

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setFocusable(false);
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ TOA THUỐC");
        pnlRight.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        lblThuoc.setBackground(new java.awt.Color(102, 102, 102));
        lblThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QuanLyPhongKham/Icon/icons8_clinic_30px.png"))); // NOI18N
        lblThuoc.setToolTipText("DANH SÁCH THUỐC");
        lblThuoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        lblThuoc.setOpaque(true);
        lblThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuocMouseClicked(evt);
            }
        });
        pnlRight.add(lblThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 40));

        lblDSPhieuKham.setBackground(new java.awt.Color(102, 102, 102));
        lblDSPhieuKham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDSPhieuKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/QuanLyPhongKham/Icon/icons8_list_30px.png"))); // NOI18N
        lblDSPhieuKham.setToolTipText("DANH SÁCH DỊCH VỤ");
        lblDSPhieuKham.setOpaque(true);
        lblDSPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDSPhieuKhamMouseClicked(evt);
            }
        });
        pnlRight.add(lblDSPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 40));

        pnlCard.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(0, 0, 0)));
        pnlCard.setLayout(new java.awt.CardLayout());

        pnlThuoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiemTenThuoc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtTimKiemTenThuoc.setText("Tìm Kiếm Tên Thuốc:");
        pnlThuoc.add(txtTimKiemTenThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, 30));

        cboLoaiThuoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cboLoaiThuoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiThuocItemStateChanged(evt);
            }
        });
        pnlThuoc.add(cboLoaiThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 30));

        tblDSThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Thuốc", "Tên Thuốc", "ĐVT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSThuoc.setAltoHead(35);
        tblDSThuoc.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblDSThuoc.setColorSelBackgound(new java.awt.Color(255, 0, 0));
        tblDSThuoc.setFuenteHead(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tblDSThuoc.setRowHeight(26);
        jScrollPane1.setViewportView(tblDSThuoc);
        if (tblDSThuoc.getColumnModel().getColumnCount() > 0) {
            tblDSThuoc.getColumnModel().getColumn(0).setMinWidth(100);
            tblDSThuoc.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblDSThuoc.getColumnModel().getColumn(0).setMaxWidth(100);
            tblDSThuoc.getColumnModel().getColumn(2).setMinWidth(100);
            tblDSThuoc.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblDSThuoc.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        pnlThuoc.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 600, 430));

        lblThoaiThuoc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblThoaiThuoc.setText("Loại Thuốc: ");
        pnlThuoc.add(lblThoaiThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txtTimKiemThuoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTimKiemThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemThuocKeyReleased(evt);
            }
        });
        pnlThuoc.add(txtTimKiemThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 270, 30));

        pnlCard.add(pnlThuoc, "card2");

        pnlDSPhieuKham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiemDichVu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTimKiemDichVu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemDichVuKeyReleased(evt);
            }
        });
        pnlDSPhieuKham.add(txtTimKiemDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 40));

        tblDSPhieuKham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã PK", "Ngày Khám", "Mã BS", "Mã BN", "Mã NV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSPhieuKham.setAltoHead(35);
        tblDSPhieuKham.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblDSPhieuKham.setColorSelBackgound(new java.awt.Color(255, 0, 0));
        tblDSPhieuKham.setFuenteHead(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tblDSPhieuKham.setRowHeight(26);
        jScrollPane2.setViewportView(tblDSPhieuKham);
        if (tblDSPhieuKham.getColumnModel().getColumnCount() > 0) {
            tblDSPhieuKham.getColumnModel().getColumn(0).setMinWidth(80);
            tblDSPhieuKham.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblDSPhieuKham.getColumnModel().getColumn(0).setMaxWidth(80);
            tblDSPhieuKham.getColumnModel().getColumn(2).setMinWidth(100);
            tblDSPhieuKham.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblDSPhieuKham.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        pnlDSPhieuKham.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 580, 440));

        btnTim.setText("Tìm Kiếm");
        pnlDSPhieuKham.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, -1));

        pnlCard.add(pnlDSPhieuKham, "card3");

        pnlRight.add(pnlCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 600, 520));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Thông Tin Bệnh Nhân:");
        pnlRight.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 450, 30));

        pnlHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "THUỐC", "ĐVT", "SL", "CÁCH DÙNG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setAltoHead(35);
        tblHoaDon.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        tblHoaDon.setColorFilasForeground2(new java.awt.Color(255, 0, 0));
        tblHoaDon.setColorSelBackgound(new java.awt.Color(255, 0, 0));
        tblHoaDon.setFillsViewportHeight(true);
        tblHoaDon.setFuenteHead(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tblHoaDon.setGrosorBordeFilas(0);
        tblHoaDon.setGrosorBordeHead(0);
        tblHoaDon.setRowHeight(30);
        jScrollPane3.setViewportView(tblHoaDon);
        if (tblHoaDon.getColumnModel().getColumnCount() > 0) {
            tblHoaDon.getColumnModel().getColumn(1).setMinWidth(80);
            tblHoaDon.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblHoaDon.getColumnModel().getColumn(1).setMaxWidth(80);
            tblHoaDon.getColumnModel().getColumn(2).setMinWidth(70);
            tblHoaDon.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblHoaDon.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoaDonLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
        );

        pnlRight.add(pnlHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 560, 520));

        btnThem.setText("THÊM");
        pnlRight.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 730, 90, -1));

        btnInHoaDon.setText("IN HOÁ ĐƠN");
        pnlRight.add(btnInHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 730, 130, -1));

        btnDanhSachHoaDon.setText("DANH SÁCH HOÁ ĐƠN");
        pnlRight.add(btnDanhSachHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 730, -1, -1));

        pnlTong.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 1190, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x = 210;
    int i = 0;
    private void lblDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseClicked
        if (x == 210) {
            pnlLeft.setSize(210, 790);
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        for (i = 210; i >= 60; i--) {
                            Thread.sleep(1, 5);
                            pnlLeft.setSize(i, 790);
                            pnlRight.setLocation(60, 100);
                            pnlRight.setSize(1340, 790);
                            btnDangXuat.show(false);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            th.start();
            x = 60;
        } else if (x == 60) {
            pnlLeft.setSize(x, 790);
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        for (i = 60; i <= x; i++) {
                            Thread.sleep(1);
                            pnlLeft.setSize(i, 790);
                            pnlRight.setLocation(210, 110);
                            pnlRight.setSize(1190, 790);
                            btnDangXuat.show(true);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            th.start();
            x = 210;
        }
    }//GEN-LAST:event_lblDanhMucMouseClicked

    private void lblIconNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseClicked
        this.OpenNhanVien();
    }//GEN-LAST:event_lblIconNhanVienMouseClicked

    private void lblQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseClicked
        this.OpenNhanVien();
    }//GEN-LAST:event_lblQuanLyNhanVienMouseClicked

    private void lblIconBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseClicked
        this.OpenBacSi();
    }//GEN-LAST:event_lblIconBacSiMouseClicked

    private void lblQuanLyBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseClicked
        this.OpenBacSi();
    }//GEN-LAST:event_lblQuanLyBacSiMouseClicked

    private void lblIconHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseClicked
        //this.OpenHoaDon();
    }//GEN-LAST:event_lblIconHoaDonMouseClicked

    private void lblQuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseClicked
        //this.OpenHoaDon();
    }//GEN-LAST:event_lblQuanLyHoaDonMouseClicked

    private void lblIconBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseClicked
        this.OpenBenhNhan();
    }//GEN-LAST:event_lblIconBenhNhanMouseClicked

    private void lblQuanLyBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseClicked
        this.OpenBenhNhan();
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseClicked

    private void lblIconPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseClicked
        this.OpenPhieuKham();
    }//GEN-LAST:event_lblIconPhieuKhamMouseClicked

    private void lblQuanLyPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseClicked
        this.OpenPhieuKham();
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseClicked

    private void lblIconThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseClicked
        this.OpenThongKe();
    }//GEN-LAST:event_lblIconThongKeMouseClicked

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        this.OpenThongKe();
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblIconThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseClicked
        this.OpenThuoc();
    }//GEN-LAST:event_lblIconThuocMouseClicked

    private void lblQuanLyThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseClicked
        this.OpenThuoc();
    }//GEN-LAST:event_lblQuanLyThuocMouseClicked

    private void lblIconBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseEntered
        hover(lblIconBacSi);
    }//GEN-LAST:event_lblIconBacSiMouseEntered

    private void lblIconBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseExited
        NotHover(lblIconBacSi);
    }//GEN-LAST:event_lblIconBacSiMouseExited

    private void lblIconNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseEntered
        hover(lblIconNhanVien);
    }//GEN-LAST:event_lblIconNhanVienMouseEntered

    private void lblIconNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseExited
        NotHover(lblIconNhanVien);
    }//GEN-LAST:event_lblIconNhanVienMouseExited

    private void lblIconBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseEntered
        hover(lblIconBenhNhan);
    }//GEN-LAST:event_lblIconBenhNhanMouseEntered

    private void lblIconBenhNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseExited
        NotHover(lblIconBenhNhan);
    }//GEN-LAST:event_lblIconBenhNhanMouseExited

    private void lblIconHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseEntered
        //hover(lblIconHoaDon);
    }//GEN-LAST:event_lblIconHoaDonMouseEntered

    private void lblIconHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseExited
        //NotHover(lblIconHoaDon);
    }//GEN-LAST:event_lblIconHoaDonMouseExited

    private void lblIconPhieuKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseEntered
        hover(lblIconPhieuKham);
    }//GEN-LAST:event_lblIconPhieuKhamMouseEntered

    private void lblIconPhieuKhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseExited
        NotHover(lblIconPhieuKham);
    }//GEN-LAST:event_lblIconPhieuKhamMouseExited

    private void lblIconThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseEntered
        hover(lblIconThuoc);
    }//GEN-LAST:event_lblIconThuocMouseEntered

    private void lblIconThuocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseExited
        NotHover(lblIconThuoc);
    }//GEN-LAST:event_lblIconThuocMouseExited

    private void lblIconThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseEntered
        hover(lblIconThongKe);
    }//GEN-LAST:event_lblIconThongKeMouseEntered

    private void lblIconThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseExited
        NotHover(lblIconThongKe);
    }//GEN-LAST:event_lblIconThongKeMouseExited

    private void lblDanhMucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseEntered
        hover(lblDanhMuc);
    }//GEN-LAST:event_lblDanhMucMouseEntered

    private void lblDanhMucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseExited
        NotHover(lblDanhMuc);
    }//GEN-LAST:event_lblDanhMucMouseExited

    private void lblQuanLyBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseEntered
        hoverPanel(pnlQuanLyBacSi, lblIconBacSi);

    }//GEN-LAST:event_lblQuanLyBacSiMouseEntered

    private void lblQuanLyBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseExited
        NotHoverPanel(pnlQuanLyBacSi, lblIconBacSi);

    }//GEN-LAST:event_lblQuanLyBacSiMouseExited

    private void lblQuanLyNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseEntered
        hoverPanel(pnlQuanLyNhanVien, lblIconNhanVien);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseEntered

    private void lblQuanLyNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseExited
        NotHoverPanel(pnlQuanLyNhanVien, lblIconNhanVien);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseExited

    private void lblQuanLyBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseEntered
        hoverPanel(pnlQuanLyBenhNhan, lblIconBenhNhan);
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseEntered

    private void lblQuanLyBenhNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseExited
        NotHoverPanel(pnlQuanLyBenhNhan, lblIconBenhNhan);
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseExited

    private void lblQuanLyHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseEntered
//       hoverPanel(pnlQuanLyHoaDon,lblIconHoaDon);
    }//GEN-LAST:event_lblQuanLyHoaDonMouseEntered

    private void lblQuanLyHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseExited
//       NotHoverPanel(pnlQuanLyHoaDon,lblIconHoaDon);
    }//GEN-LAST:event_lblQuanLyHoaDonMouseExited

    private void lblQuanLyPhieuKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseEntered
        hoverPanel(pnlQuanLyPhieuKham, lblIconPhieuKham);
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseEntered

    private void lblQuanLyPhieuKhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseExited
        NotHoverPanel(pnlQuanLyPhieuKham, lblIconPhieuKham);
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseExited

    private void lblQuanLyThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseEntered
        hoverPanel(pnlQuanLyThuoc, lblIconThuoc);
    }//GEN-LAST:event_lblQuanLyThuocMouseEntered

    private void lblQuanLyThuocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseExited
        NotHoverPanel(pnlQuanLyThuoc, lblIconThuoc);
    }//GEN-LAST:event_lblQuanLyThuocMouseExited

    private void lblThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseEntered
        hoverPanel(pnlQuanLyThongKe, lblIconThongKe);
    }//GEN-LAST:event_lblThongKeMouseEntered

    private void lblThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseExited
        NotHoverPanel(pnlQuanLyThongKe, lblIconThongKe);
    }//GEN-LAST:event_lblThongKeMouseExited

    private void lblIconDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconDichVuMouseClicked
        this.OpenDichVu();
    }//GEN-LAST:event_lblIconDichVuMouseClicked

    private void lblIconDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconDichVuMouseEntered
        hover(lblIconDichVu);
    }//GEN-LAST:event_lblIconDichVuMouseEntered

    private void lblIconDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconDichVuMouseExited
        NotHover(lblIconDichVu);
    }//GEN-LAST:event_lblIconDichVuMouseExited

    private void lblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseClicked
        this.OpenDichVu();
    }//GEN-LAST:event_lblDichVuMouseClicked

    private void lblDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseEntered
        hoverPanel(pnlDichVu, lblIconDichVu);
    }//GEN-LAST:event_lblDichVuMouseEntered

    private void lblDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseExited
        NotHoverPanel(pnlDichVu, lblIconDichVu);
    }//GEN-LAST:event_lblDichVuMouseExited

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.OpenLogin();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void lblThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuocMouseClicked
        this.showbtn1();
    }//GEN-LAST:event_lblThuocMouseClicked

    private void cboLoaiThuocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiThuocItemStateChanged
        this.fillDSthuoc();
    }//GEN-LAST:event_cboLoaiThuocItemStateChanged

    private void txtTimKiemThuocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemThuocKeyReleased
        if (txtTimKiemThuoc.getText().length() > 0) {
            this.fillDSthuoc();
        } else {
            this.fillDSthuoc();
        }
    }//GEN-LAST:event_txtTimKiemThuocKeyReleased

    private void txtTimKiemDichVuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemDichVuKeyReleased
        if (txtTimKiemDichVu.getText().length() > 0) {
            this.fillPhieuKham();
        } else {
            this.fillPhieuKham();
        }
    }//GEN-LAST:event_txtTimKiemDichVuKeyReleased

    private void lblDSPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDSPhieuKhamMouseClicked
        this.showbtn2();
    }//GEN-LAST:event_lblDSPhieuKhamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyToaThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover btnDangXuat;
    private rojeru_san.complementos.RSButtonHover btnDanhSachHoaDon;
    private rojeru_san.complementos.RSButtonHover btnInHoaDon;
    private rojeru_san.complementos.RSButtonHover btnThem;
    private rojeru_san.complementos.RSButtonHover btnTim;
    private javax.swing.JComboBox<String> cboLoaiThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private rojerusan.RSFotoCircle lblAnhNV;
    private javax.swing.JLabel lblDSPhieuKham;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblIconBacSi;
    private javax.swing.JLabel lblIconBenhNhan;
    private javax.swing.JLabel lblIconDichVu;
    private javax.swing.JLabel lblIconHoaDon;
    private javax.swing.JLabel lblIconNhanVien;
    private javax.swing.JLabel lblIconPhieuKham;
    private javax.swing.JLabel lblIconThongKe;
    private javax.swing.JLabel lblIconThuoc;
    private javax.swing.JLabel lblQuanLyBacSi;
    private javax.swing.JLabel lblQuanLyBenhNhan;
    private javax.swing.JLabel lblQuanLyHoaDon;
    private javax.swing.JLabel lblQuanLyNhanVien;
    private javax.swing.JLabel lblQuanLyPhieuKham;
    private javax.swing.JLabel lblQuanLyThuoc;
    private javax.swing.JLabel lblThoaiThuoc;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblThuoc;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblXinChao;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlDSPhieuKham;
    private javax.swing.JPanel pnlDichVu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlQuanLyBacSi;
    private javax.swing.JPanel pnlQuanLyBenhNhan;
    private javax.swing.JPanel pnlQuanLyHoaDon;
    private javax.swing.JPanel pnlQuanLyNhanVien;
    private javax.swing.JPanel pnlQuanLyPhieuKham;
    private javax.swing.JPanel pnlQuanLyThongKe;
    private javax.swing.JPanel pnlQuanLyThuoc;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlThuoc;
    private javax.swing.JPanel pnlTong;
    private rojeru_san.complementos.RSTableMetro tblDSPhieuKham;
    private rojeru_san.complementos.RSTableMetro tblDSThuoc;
    private rojeru_san.complementos.RSTableMetro tblHoaDon;
    private javax.swing.JTextField txtTimKiemDichVu;
    private javax.swing.JLabel txtTimKiemTenThuoc;
    private javax.swing.JTextField txtTimKiemThuoc;
    // End of variables declaration//GEN-END:variables

    loaithuocDAO ltdao = new loaithuocDAO();
    thuocDAO thdao = new thuocDAO();
    phieukhamDAO pkdao = new phieukhamDAO();

    private void init() {
        hover(lblThuoc);
        setLocationRelativeTo(null);
        this.LoadNgay();
        this.fillComBoBoxLoaiThuoc();
        this.fillDSthuoc();
        this.fillPhieuKham();
    }

    //Hover màu
    private void hover(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void NotHover(JLabel lbl) {
        lbl.setBackground(new java.awt.Color(54, 70, 78));
    }

    private void hoverPanel(JPanel pnl, JLabel lbl) {
        pnl.setBackground(new java.awt.Color(53, 162, 107));
        lbl.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void NotHoverPanel(JPanel pnl, JLabel lbl) {
        pnl.setBackground(new java.awt.Color(54, 70, 78));
        lbl.setBackground(new java.awt.Color(54, 70, 78));
    }

    private void LoadNgay() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String day = sdf.format(date);
        lblDay.setText(day);
    }

    private void showbtn1() {
        pnlThuoc.show();
        pnlDSPhieuKham.show(false);
        lblThuoc.setBackground(new java.awt.Color(53, 162, 107));
        lblDSPhieuKham.setBackground(new java.awt.Color(102, 102, 102));
    }

    private void showbtn2() {
        pnlDSPhieuKham.show();
        pnlThuoc.show(false);
        lblDSPhieuKham.setBackground(new java.awt.Color(53, 162, 107));
        lblThuoc.setBackground(new java.awt.Color(102, 102, 102));
    }

//   
    private void OpenBacSi() {
        this.dispose();
        new QuanLyBacSi().setVisible(true);
    }

    private void OpenBenhNhan() {
        this.dispose();
        new QuanLyBenhNhan().setVisible(true);
    }

    private void OpenNhanVien() {
        this.dispose();
        new QuanLyNhanVien().setVisible(true);
    }

    private void OpenHoaDon() {
        this.dispose();
        new QuanLyToaThuoc().setVisible(true);
    }

    private void OpenPhieuKham() {
        this.dispose();
        new QuanLyPhieuKham().setVisible(true);
    }

    private void OpenThuoc() {
        this.dispose();
        new QuanLyThuoc().setVisible(true);
    }

    private void OpenDichVu() {
        this.dispose();
        new QuanLyDichVu().setVisible(true);
    }

    private void OpenLogin() {
        this.dispose();
        new dangnhap().setVisible(true);
    }

    private void OpenThongKe() {
        this.dispose();
        new ThongKe().setVisible(true);
    }

    private void fillComBoBoxLoaiThuoc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiThuoc.getModel();
        model.removeAllElements();
        try {
            List<LoaiThuoc> list = ltdao.SelectAll();
            for (LoaiThuoc lt : list) {
                model.addElement(lt);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillDSthuoc() {
        DefaultTableModel model = (DefaultTableModel) tblDSThuoc.getModel();
        model.setRowCount(0);
        try {
            LoaiThuoc loaithuoc = (LoaiThuoc) cboLoaiThuoc.getSelectedItem();
            String text = txtTimKiemThuoc.getText();
            List<Thuoc> list = thdao.SearchtoMaLoaiThuoc(loaithuoc.getMaloaithuoc(), text, text, text);
            for (Thuoc th : list) {
                model.addRow(new Object[]{
                    th.getMaThuoc(), th.getTenthuoc(), th.getDonvitinh()
                });
            }
            model.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillPhieuKham() {
        DefaultTableModel model = (DefaultTableModel) tblDSPhieuKham.getModel();
        model.setRowCount(0);
        try {
            String text = txtTimKiemDichVu.getText();
            List<PhieuKham> list = pkdao.Search(text, text, text);
            for (PhieuKham pk : list) {
                model.addRow(new Object[]{
                    pk.getMaphieukham(), XDate.toString(pk.getNgaykham(), "dd/MM/yyyy"), pk.getMabacsy(), pk.getMabenhnhan(), pk.getManhanvien()
                });
            }
            model.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
