/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.QuanLyPhongKham.UI;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author OS
 */
public class QuanLyToaThuoc extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyPhongKham
     */
    public QuanLyToaThuoc() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTong = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblXinChao = new javax.swing.JLabel();
        lblTieuDe = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAnhNV = new rojerusan.RSFotoCircle();
        pnlLeft = new javax.swing.JPanel();
        lblDanhMuc = new javax.swing.JLabel();
        pnlQuanLyBacSi = new javax.swing.JPanel();
        lblIconBacSi = new javax.swing.JLabel();
        lblQuanLyBacSi = new javax.swing.JLabel();
        pnlQuanLyNhanVien = new javax.swing.JPanel();
        lblIconNhanVien = new javax.swing.JLabel();
        lblQuanLyNhanVien = new javax.swing.JLabel();
        pnlQuanLyBenhNhan = new javax.swing.JPanel();
        lblIconBenhNhan = new javax.swing.JLabel();
        lblQuanLyBenhNhan = new javax.swing.JLabel();
        pnlQuanLyHoaDon = new javax.swing.JPanel();
        lblIconHoaDon = new javax.swing.JLabel();
        lblQuanLyHoaDon = new javax.swing.JLabel();
        pnlQuanLyPhieuKham = new javax.swing.JPanel();
        lblIconPhieuKham = new javax.swing.JLabel();
        lblQuanLyPhieuKham = new javax.swing.JLabel();
        pnlQuanLyThuoc = new javax.swing.JPanel();
        lblIconThuoc = new javax.swing.JLabel();
        lblQuanLyThuoc = new javax.swing.JLabel();
        pnlQuanLyThongKe = new javax.swing.JPanel();
        lblIconThongKe = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnHocVien = new rojeru_san.complementos.RSButtonHover();
        btnNguoiHoc = new rojeru_san.complementos.RSButtonHover();
        pnlCard = new javax.swing.JPanel();
        pnlToaThuoc = new javax.swing.JPanel();
        pnlBacSi = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnlPhieuKham = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblMaChuyenNganh = new javax.swing.JLabel();
        lblLieuLuong = new javax.swing.JLabel();
        lblMaChuyenNganh2 = new javax.swing.JLabel();
        lblMaChuyenNganh3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        rSTableMetro2 = new rojeru_san.complementos.RSTableMetro();
        pnlDSThuoc = new javax.swing.JPanel();
        pnlKhoaHoc2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ PHÒNG KHÁM");

        pnlTong.setBackground(new java.awt.Color(255, 255, 255));
        pnlTong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(51, 153, 255));

        lblXinChao.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lblXinChao.setText("Xin chào, ");

        lblTieuDe.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDe.setText("PHÒNG KHÁM AN NHIÊN");

        lblDay.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDay.setText("dd/MM/yyyy");

        lblTime.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("00:00  SA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANG ĐẾN SỰ BÌNH YÊN");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addGap(35, 35, 35))))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addComponent(lblTieuDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTime))
                    .addComponent(lblAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblXinChao)
                .addGap(34, 34, 34))
        );

        pnlTong.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 100));

        pnlLeft.setBackground(new java.awt.Color(54, 70, 78));
        pnlLeft.setForeground(new java.awt.Color(54, 70, 78));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDanhMuc.setBackground(new java.awt.Color(54, 70, 78));
        lblDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-menu-30.png"))); // NOI18N
        lblDanhMuc.setOpaque(true);
        lblDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDanhMucMouseExited(evt);
            }
        });
        pnlLeft.add(lblDanhMuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 40));

        pnlQuanLyBacSi.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyBacSi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconBacSi.setBackground(new java.awt.Color(54, 70, 78));
        lblIconBacSi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconBacSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_doctor_male_30px.png"))); // NOI18N
        lblIconBacSi.setToolTipText("Quản Lý Bác Sĩ");
        lblIconBacSi.setOpaque(true);
        lblIconBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconBacSiMouseExited(evt);
            }
        });
        pnlQuanLyBacSi.add(lblIconBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyBacSi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyBacSi.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyBacSi.setText("Quản Lý Bác Sĩ");
        lblQuanLyBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyBacSiMouseExited(evt);
            }
        });
        pnlQuanLyBacSi.add(lblQuanLyBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 210, 40));

        pnlQuanLyNhanVien.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconNhanVien.setBackground(new java.awt.Color(54, 70, 78));
        lblIconNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_manager_30px.png"))); // NOI18N
        lblIconNhanVien.setToolTipText("Quản Lý Nhân Viên");
        lblIconNhanVien.setOpaque(true);
        lblIconNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconNhanVienMouseExited(evt);
            }
        });
        pnlQuanLyNhanVien.add(lblIconNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyNhanVien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyNhanVien.setText("Quản Lý Nhân Viên");
        lblQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanVienMouseExited(evt);
            }
        });
        pnlQuanLyNhanVien.add(lblQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 40));

        pnlQuanLyBenhNhan.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyBenhNhan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconBenhNhan.setBackground(new java.awt.Color(54, 70, 78));
        lblIconBenhNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-male-user-23.png"))); // NOI18N
        lblIconBenhNhan.setToolTipText("Quản Lý Bệnh Nhân");
        lblIconBenhNhan.setOpaque(true);
        lblIconBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconBenhNhanMouseExited(evt);
            }
        });
        pnlQuanLyBenhNhan.add(lblIconBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyBenhNhan.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyBenhNhan.setText("Quản Lý Bệnh Nhân");
        lblQuanLyBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyBenhNhanMouseExited(evt);
            }
        });
        pnlQuanLyBenhNhan.add(lblQuanLyBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyBenhNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 40));

        pnlQuanLyHoaDon.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconHoaDon.setBackground(new java.awt.Color(54, 70, 78));
        lblIconHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_dollar_place_marker_30px.png"))); // NOI18N
        lblIconHoaDon.setToolTipText("Quản Lý Hoá Đơn");
        lblIconHoaDon.setOpaque(true);
        lblIconHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconHoaDonMouseExited(evt);
            }
        });
        pnlQuanLyHoaDon.add(lblIconHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyHoaDon.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyHoaDon.setText("Quản Lý Hoá Đơn");
        lblQuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyHoaDonMouseExited(evt);
            }
        });
        pnlQuanLyHoaDon.add(lblQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 40));

        pnlQuanLyPhieuKham.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyPhieuKham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconPhieuKham.setBackground(new java.awt.Color(54, 70, 78));
        lblIconPhieuKham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPhieuKham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_ticket_30px.png"))); // NOI18N
        lblIconPhieuKham.setToolTipText("Quản Lý Phiếu Khám");
        lblIconPhieuKham.setOpaque(true);
        lblIconPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconPhieuKhamMouseExited(evt);
            }
        });
        pnlQuanLyPhieuKham.add(lblIconPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyPhieuKham.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyPhieuKham.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyPhieuKham.setText("Quản Lý Phiếu Khám\n");
        lblQuanLyPhieuKham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyPhieuKhamMouseExited(evt);
            }
        });
        pnlQuanLyPhieuKham.add(lblQuanLyPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 20));

        pnlLeft.add(pnlQuanLyPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 210, 40));

        pnlQuanLyThuoc.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThuoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThuoc.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThuoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_clinic_30px.png"))); // NOI18N
        lblIconThuoc.setToolTipText("Quản Lý Thuốc");
        lblIconThuoc.setOpaque(true);
        lblIconThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThuocMouseExited(evt);
            }
        });
        pnlQuanLyThuoc.add(lblIconThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblQuanLyThuoc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblQuanLyThuoc.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLyThuoc.setText("Quản Lý Thuốc");
        lblQuanLyThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyThuocMouseExited(evt);
            }
        });
        pnlQuanLyThuoc.add(lblQuanLyThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 40));

        pnlQuanLyThongKe.setBackground(new java.awt.Color(54, 70, 78));
        pnlQuanLyThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconThongKe.setBackground(new java.awt.Color(54, 70, 78));
        lblIconThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-increase-23.png"))); // NOI18N
        lblIconThongKe.setToolTipText("Quản Lý Thống Kê");
        lblIconThongKe.setOpaque(true);
        lblIconThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIconThongKeMouseExited(evt);
            }
        });
        pnlQuanLyThongKe.add(lblIconThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        lblThongKe.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKe.setText("Thống Kê");
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeMouseExited(evt);
            }
        });
        pnlQuanLyThongKe.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 20));

        pnlLeft.add(pnlQuanLyThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 40));

        pnlTong.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, 660));

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setFocusable(false);
        pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUẢN LÝ TOA THUỐC");
        pnlRight.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        btnHocVien.setBackground(new java.awt.Color(51, 153, 255));
        btnHocVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        btnHocVien.setText("TOA THUỐC");
        btnHocVien.setOpaque(true);
        btnHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHocVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHocVienMouseExited(evt);
            }
        });
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });
        pnlRight.add(btnHocVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));

        btnNguoiHoc.setBackground(new java.awt.Color(51, 153, 255));
        btnNguoiHoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, new java.awt.Color(255, 255, 255)));
        btnNguoiHoc.setText("THUỐC");
        btnNguoiHoc.setOpaque(true);
        btnNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNguoiHocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNguoiHocMouseExited(evt);
            }
        });
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });
        pnlRight.add(btnNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, -1));

        pnlCard.setLayout(new java.awt.CardLayout());

        pnlToaThuoc.setBackground(new java.awt.Color(255, 255, 255));
        pnlToaThuoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBacSi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BÁC SĨ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(0, 120, 215))); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlBacSiLayout = new javax.swing.GroupLayout(pnlBacSi);
        pnlBacSi.setLayout(pnlBacSiLayout);
        pnlBacSiLayout.setHorizontalGroup(
            pnlBacSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBacSiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(500, 500, 500))
        );
        pnlBacSiLayout.setVerticalGroup(
            pnlBacSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBacSiLayout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlToaThuoc.add(pnlBacSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 390, 80));

        pnlPhieuKham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PHIẾU KHÁM", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(0, 120, 215))); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlPhieuKhamLayout = new javax.swing.GroupLayout(pnlPhieuKham);
        pnlPhieuKham.setLayout(pnlPhieuKhamLayout);
        pnlPhieuKhamLayout.setHorizontalGroup(
            pnlPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhieuKhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(480, 480, 480))
        );
        pnlPhieuKhamLayout.setVerticalGroup(
            pnlPhieuKhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhieuKhamLayout.createSequentialGroup()
                .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlToaThuoc.add(pnlPhieuKham, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 380, 80));

        lblMaChuyenNganh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaChuyenNganh.setForeground(new java.awt.Color(255, 51, 51));
        lblMaChuyenNganh.setText("dd/MM/yyyy");
        pnlToaThuoc.add(lblMaChuyenNganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 200, 30));

        lblLieuLuong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblLieuLuong.setText("Liều Lượng");
        pnlToaThuoc.add(lblLieuLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 110, 30));

        lblMaChuyenNganh2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaChuyenNganh2.setText("Ngày Kê");
        pnlToaThuoc.add(lblMaChuyenNganh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 80, 30));

        lblMaChuyenNganh3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaChuyenNganh3.setText("Tên Thuốc");
        pnlToaThuoc.add(lblMaChuyenNganh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 90, 30));

        jList1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jScrollPane2.setViewportView(jList1);

        pnlToaThuoc.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 250, 160));

        jList2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setToolTipText("");
        jScrollPane3.setViewportView(jList2);

        pnlToaThuoc.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 350, 160));

        btnThem.setBackground(new java.awt.Color(0, 112, 192));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 35));

        btnSua.setBackground(new java.awt.Color(0, 112, 192));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 80, 35));

        btnXoa.setBackground(new java.awt.Color(0, 112, 192));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("XOÁ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 80, 35));

        btnMoi.setBackground(new java.awt.Color(0, 112, 192));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 80, 35));

        btnFirst.setBackground(new java.awt.Color(0, 112, 192));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 80, 35));

        btnPrevious.setBackground(new java.awt.Color(0, 112, 192));
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 80, 35));

        btnNext.setBackground(new java.awt.Color(0, 112, 192));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 80, 35));

        btnLast.setBackground(new java.awt.Color(0, 112, 192));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlToaThuoc.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 80, 35));

        rSTableMetro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetro2.setAltoHead(30);
        rSTableMetro2.setRowHeight(22);
        jScrollPane4.setViewportView(rSTableMetro2);

        pnlToaThuoc.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 860, 240));

        pnlCard.add(pnlToaThuoc, "card2");

        pnlDSThuoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlKhoaHoc2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÊN THUỐC", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(0, 120, 215))); // NOI18N

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlKhoaHoc2Layout = new javax.swing.GroupLayout(pnlKhoaHoc2);
        pnlKhoaHoc2.setLayout(pnlKhoaHoc2Layout);
        pnlKhoaHoc2Layout.setHorizontalGroup(
            pnlKhoaHoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhoaHoc2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlKhoaHoc2Layout.setVerticalGroup(
            pnlKhoaHoc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKhoaHoc2Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDSThuoc.add(pnlKhoaHoc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 840, 80));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetro1.setAltoHead(35);
        rSTableMetro1.setRowHeight(26);
        jScrollPane1.setViewportView(rSTableMetro1);

        pnlDSThuoc.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 870, -1));

        pnlCard.add(pnlDSThuoc, "card3");

        pnlRight.add(pnlCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 950, 580));

        pnlTong.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 990, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int x = 210;
    int i=0;
    private void lblDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseClicked
       if ( x == 210 ) {
            pnlLeft.setSize(210, 760);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try {
                        
                        for ( int i = 210; i >= 60; i--){
                            Thread.sleep(1);
                            pnlLeft.setSize(i, 760);
                            pnlRight.setLocation(60, 100);
                            pnlRight.setSize(1140, 760);
                            
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x = 60;
//            ImageIcon icon1 = new ImageIcon("C:\\Github\\DuAn1_QuanLyPhongKham\\DuAn1_QuanLyPhongKham\\src\\Icon\\icons8_chevron_right_30px.png");
//            lblDanhMuc.setIcon(icon1);
        } 
        else if( x == 60 ){
            pnlLeft.setSize(x, 760);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try {
                        for (int i = 60; i <= x; i++){
                            Thread.sleep(1);
                            pnlLeft.setSize(i, 760);
                            pnlRight.setLocation(210, 100);
                            pnlRight.setSize(990, 760);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };th.start();
            x = 210;
//            ImageIcon icon = new ImageIcon("C:\\Github\\DuAn1_QuanLyPhongKham\\DuAn1_QuanLyPhongKham\\src\\Icon\\icons8-menu-30.png");
//            lblDanhMuc.setIcon(icon);
        }
    }//GEN-LAST:event_lblDanhMucMouseClicked

    private void lblIconNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseClicked
        
    }//GEN-LAST:event_lblIconNhanVienMouseClicked

    private void lblQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseClicked
        
    }//GEN-LAST:event_lblQuanLyNhanVienMouseClicked

    private void lblIconBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconBacSiMouseClicked

    private void lblQuanLyBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseClicked
        
    }//GEN-LAST:event_lblQuanLyBacSiMouseClicked

    private void lblIconHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconHoaDonMouseClicked

    private void lblQuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuanLyHoaDonMouseClicked

    private void lblIconBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconBenhNhanMouseClicked

    private void lblQuanLyBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseClicked

    private void lblIconPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconPhieuKhamMouseClicked

    private void lblQuanLyPhieuKhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseClicked

    private void lblIconThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThongKeMouseClicked

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblIconThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconThuocMouseClicked

    private void lblQuanLyThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuanLyThuocMouseClicked

    private void lblIconBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseEntered
        hover(lblIconBacSi);
    }//GEN-LAST:event_lblIconBacSiMouseEntered

    private void lblIconBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBacSiMouseExited
        NotHover(lblIconBacSi);
    }//GEN-LAST:event_lblIconBacSiMouseExited

    private void lblIconNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseEntered
        hover(lblIconNhanVien);
    }//GEN-LAST:event_lblIconNhanVienMouseEntered

    private void lblIconNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconNhanVienMouseExited
        NotHover(lblIconNhanVien);
    }//GEN-LAST:event_lblIconNhanVienMouseExited

    private void lblIconBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseEntered
        hover(lblIconBenhNhan);
    }//GEN-LAST:event_lblIconBenhNhanMouseEntered

    private void lblIconBenhNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconBenhNhanMouseExited
        NotHover(lblIconBenhNhan);
    }//GEN-LAST:event_lblIconBenhNhanMouseExited

    private void lblIconHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseEntered
        hover(lblIconHoaDon);
    }//GEN-LAST:event_lblIconHoaDonMouseEntered

    private void lblIconHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconHoaDonMouseExited
        NotHover(lblIconHoaDon);
    }//GEN-LAST:event_lblIconHoaDonMouseExited

    private void lblIconPhieuKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseEntered
        hover(lblIconPhieuKham);
    }//GEN-LAST:event_lblIconPhieuKhamMouseEntered

    private void lblIconPhieuKhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconPhieuKhamMouseExited
        NotHover(lblIconPhieuKham);
    }//GEN-LAST:event_lblIconPhieuKhamMouseExited

    private void lblIconThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseEntered
        hover(lblIconThuoc);
    }//GEN-LAST:event_lblIconThuocMouseEntered

    private void lblIconThuocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThuocMouseExited
        NotHover(lblIconThuoc);
    }//GEN-LAST:event_lblIconThuocMouseExited

    private void lblIconThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseEntered
        hover(lblIconThongKe);
    }//GEN-LAST:event_lblIconThongKeMouseEntered

    private void lblIconThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconThongKeMouseExited
        NotHover(lblIconThongKe);
    }//GEN-LAST:event_lblIconThongKeMouseExited

    private void lblDanhMucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseEntered
        hover(lblDanhMuc);
    }//GEN-LAST:event_lblDanhMucMouseEntered

    private void lblDanhMucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDanhMucMouseExited
        NotHover(lblDanhMuc);
    }//GEN-LAST:event_lblDanhMucMouseExited

    private void lblQuanLyBacSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseEntered
        hoverPanel(pnlQuanLyBacSi,lblIconBacSi);
        
    }//GEN-LAST:event_lblQuanLyBacSiMouseEntered

    private void lblQuanLyBacSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBacSiMouseExited
        NotHoverPanel(pnlQuanLyBacSi,lblIconBacSi);
        
    }//GEN-LAST:event_lblQuanLyBacSiMouseExited

    private void lblQuanLyNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseEntered
        hoverPanel(pnlQuanLyNhanVien,lblIconNhanVien);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseEntered

    private void lblQuanLyNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanVienMouseExited
        NotHoverPanel(pnlQuanLyNhanVien,lblIconNhanVien);
    }//GEN-LAST:event_lblQuanLyNhanVienMouseExited

    private void lblQuanLyBenhNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseEntered
        hoverPanel(pnlQuanLyBenhNhan,lblIconBenhNhan);
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseEntered

    private void lblQuanLyBenhNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyBenhNhanMouseExited
        NotHoverPanel(pnlQuanLyBenhNhan,lblIconBenhNhan);
    }//GEN-LAST:event_lblQuanLyBenhNhanMouseExited

    private void lblQuanLyHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseEntered
       hoverPanel(pnlQuanLyHoaDon,lblIconHoaDon);
    }//GEN-LAST:event_lblQuanLyHoaDonMouseEntered

    private void lblQuanLyHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyHoaDonMouseExited
       NotHoverPanel(pnlQuanLyHoaDon,lblIconHoaDon);
    }//GEN-LAST:event_lblQuanLyHoaDonMouseExited

    private void lblQuanLyPhieuKhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseEntered
        hoverPanel(pnlQuanLyPhieuKham,lblIconPhieuKham);
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseEntered

    private void lblQuanLyPhieuKhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyPhieuKhamMouseExited
        NotHoverPanel(pnlQuanLyPhieuKham,lblIconPhieuKham);
    }//GEN-LAST:event_lblQuanLyPhieuKhamMouseExited

    private void lblQuanLyThuocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseEntered
        hoverPanel(pnlQuanLyThuoc,lblIconThuoc);
    }//GEN-LAST:event_lblQuanLyThuocMouseEntered

    private void lblQuanLyThuocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThuocMouseExited
        NotHoverPanel(pnlQuanLyThuoc,lblIconThuoc);
    }//GEN-LAST:event_lblQuanLyThuocMouseExited

    private void lblThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseEntered
        hoverPanel(pnlQuanLyThongKe,lblIconThongKe);
    }//GEN-LAST:event_lblThongKeMouseEntered

    private void lblThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseExited
        NotHoverPanel(pnlQuanLyThongKe,lblIconThongKe);
    }//GEN-LAST:event_lblThongKeMouseExited

    private void btnHocVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHocVienMouseEntered
        // TODO add your handling code here:
        //        pnlChiTietThongKe.show(false);
        //        pnlDanhSach.show(false);
        //        pnlTroGiup.show(false);
        //
        //        pnlCapNhat.show();
        //        btnHeThong.setBackground(new Color(0, 112, 192));
    }//GEN-LAST:event_btnHocVienMouseEntered

    private void btnHocVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHocVienMouseExited

        //btnHeThong.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_btnHocVienMouseExited

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        this.showbtn1();
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void btnNguoiHocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNguoiHocMouseEntered
        // TODO add your handling code here:
        //        pnlChiTietThongKe.show(false);
        //        pnlTroGiup.show(false);
        //        pnlCapNhat.show(false);
        //        pnlDanhSach.show();
        //        btnQuanLy.setBackground(new Color(0, 112, 192));
    }//GEN-LAST:event_btnNguoiHocMouseEntered

    private void btnNguoiHocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNguoiHocMouseExited
        //btnQuanLy.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_btnNguoiHocMouseExited

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        this.showbtn2();
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyToaThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyToaThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private rojeru_san.complementos.RSButtonHover btnHocVien;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private rojeru_san.complementos.RSButtonHover btnNguoiHoc;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private rojerusan.RSFotoCircle lblAnhNV;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblIconBacSi;
    private javax.swing.JLabel lblIconBenhNhan;
    private javax.swing.JLabel lblIconHoaDon;
    private javax.swing.JLabel lblIconNhanVien;
    private javax.swing.JLabel lblIconPhieuKham;
    private javax.swing.JLabel lblIconThongKe;
    private javax.swing.JLabel lblIconThuoc;
    private javax.swing.JLabel lblLieuLuong;
    private javax.swing.JLabel lblMaChuyenNganh;
    private javax.swing.JLabel lblMaChuyenNganh2;
    private javax.swing.JLabel lblMaChuyenNganh3;
    private javax.swing.JLabel lblQuanLyBacSi;
    private javax.swing.JLabel lblQuanLyBenhNhan;
    private javax.swing.JLabel lblQuanLyHoaDon;
    private javax.swing.JLabel lblQuanLyNhanVien;
    private javax.swing.JLabel lblQuanLyPhieuKham;
    private javax.swing.JLabel lblQuanLyThuoc;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblXinChao;
    private javax.swing.JPanel pnlBacSi;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlDSThuoc;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKhoaHoc2;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlPhieuKham;
    private javax.swing.JPanel pnlQuanLyBacSi;
    private javax.swing.JPanel pnlQuanLyBenhNhan;
    private javax.swing.JPanel pnlQuanLyHoaDon;
    private javax.swing.JPanel pnlQuanLyNhanVien;
    private javax.swing.JPanel pnlQuanLyPhieuKham;
    private javax.swing.JPanel pnlQuanLyThongKe;
    private javax.swing.JPanel pnlQuanLyThuoc;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlToaThuoc;
    private javax.swing.JPanel pnlTong;
    private rojeru_san.complementos.RSTableMetro rSTableMetro1;
    private rojeru_san.complementos.RSTableMetro rSTableMetro2;
    // End of variables declaration//GEN-END:variables
    private void init(){
        setLocationRelativeTo(null);
    }
    
    //Hover màu
    private void hover(JLabel lbl){
        lbl.setBackground(new java.awt.Color(53,162,107));
    }
    
    private void NotHover(JLabel lbl){
        lbl.setBackground(new java.awt.Color(54,70,78));
    }
    
    private void hoverPanel(JPanel pnl,JLabel lbl){
        pnl.setBackground(new java.awt.Color(53,162,107));
        lbl.setBackground(new java.awt.Color(53,162,107));
    }
    
    private void NotHoverPanel(JPanel pnl,JLabel lbl){
        pnl.setBackground(new java.awt.Color(54,70,78));
        lbl.setBackground(new java.awt.Color(54,70,78));
    }
    
    private void showbtn1() {
        pnlToaThuoc.show();
        pnlDSThuoc.show(false);
        btnHocVien.setBackground(new Color(51, 0, 255));
        btnNguoiHoc.setBackground(new Color(51, 153, 255));
    }

    private void showbtn2() {
        pnlDSThuoc.show();
        pnlToaThuoc.show(false);
        btnNguoiHoc.setBackground(new Color(51, 0, 255));
        btnHocVien.setBackground(new Color(51, 153, 255));
    }

    private void changecolor11(JPanel hover, Color color) {
        hover.setBackground(color);
    }
}
